/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TableRouteImport } from './routes/_table'
import { Route as EasyRouteImport } from './routes/easy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MeetingsRouteImport } from './routes/meetings'
import { Route as TableCartRouteImport } from './routes/_table/cart'
import { Route as TableDuelRouteImport } from './routes/_table/duel'
import { Route as TableEventsRouteImport } from './routes/_table/events'
import { Route as TableFloorRouteImport } from './routes/_table/floor'
import { Route as TableHallRouteImport } from './routes/_table/hall'
import { Route as TableNexusRouteImport } from './routes/_table/nexus'
import { Route as TablePennyRouteImport } from './routes/_table/penny'
import { Route as TableSellRouteImport } from './routes/_table/sell'
import { Route as TableSheetsRouteImport } from './routes/_table/sheets'
import { Route as TableVaultRouteImport } from './routes/_table/vault'
import { Route as ApiRtcRouteImport } from './routes/api/rtc'
import { Route as TableFloorTableIdRouteImport } from './routes/_table/floor.$tableId'
import { Route as TableNexusIndexRouteImport } from './routes/_table/nexus.index'
import { Route as TableNexusApproachRouteImport } from './routes/_table/nexus.approach'
import { Route as TableNexusGarageRouteImport } from './routes/_table/nexus.garage'
import { Route as TableNexusLabsRouteImport } from './routes/_table/nexus.labs'
import { Route as TableNexusMessengerRouteImport } from './routes/_table/nexus.messenger'
import { Route as TableNexusOfficeRouteImport } from './routes/_table/nexus.office'
import { Route as TableNexusPartyRouteImport } from './routes/_table/nexus.party'
import { Route as TableSheetsSheetIdRouteImport } from './routes/_table/sheets.$sheetId'
import { Route as TableVaultListingIdRouteImport } from './routes/_table/vault.$listingId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TableRoute = TableRouteImport.update({
  id: '/_table',
  getParentRoute: () => rootRouteImport,
} as any)
const EasyRoute = EasyRouteImport.update({
  id: '/easy',
  path: '/easy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsRoute = MeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const TableCartRoute = TableCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => TableRoute,
} as any)
const TableDuelRoute = TableDuelRouteImport.update({
  id: '/duel',
  path: '/duel',
  getParentRoute: () => TableRoute,
} as any)
const TableEventsRoute = TableEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => TableRoute,
} as any)
const TableFloorRoute = TableFloorRouteImport.update({
  id: '/floor',
  path: '/floor',
  getParentRoute: () => TableRoute,
} as any)
const TableHallRoute = TableHallRouteImport.update({
  id: '/hall',
  path: '/hall',
  getParentRoute: () => TableRoute,
} as any)
const TableNexusRoute = TableNexusRouteImport.update({
  id: '/nexus',
  path: '/nexus',
  getParentRoute: () => TableRoute,
} as any)
const TablePennyRoute = TablePennyRouteImport.update({
  id: '/penny',
  path: '/penny',
  getParentRoute: () => TableRoute,
} as any)
const TableSellRoute = TableSellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => TableRoute,
} as any)
const TableSheetsRoute = TableSheetsRouteImport.update({
  id: '/sheets',
  path: '/sheets',
  getParentRoute: () => TableRoute,
} as any)
const TableVaultRoute = TableVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => TableRoute,
} as any)
const ApiRtcRoute = ApiRtcRouteImport.update({
  id: '/api/rtc',
  path: '/api/rtc',
  getParentRoute: () => rootRouteImport,
} as any)
const TableFloorTableIdRoute = TableFloorTableIdRouteImport.update({
  id: '/$tableId',
  path: '/$tableId',
  getParentRoute: () => TableFloorRoute,
} as any)
const TableNexusIndexRoute = TableNexusIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TableNexusRoute,
} as any)
const TableNexusApproachRoute = TableNexusApproachRouteImport.update({
  id: '/approach',
  path: '/approach',
  getParentRoute: () => TableNexusRoute,
} as any)
const TableNexusGarageRoute = TableNexusGarageRouteImport.update({
  id: '/garage',
  path: '/garage',
  getParentRoute: () => TableNexusRoute,
} as any)
const TableNexusLabsRoute = TableNexusLabsRouteImport.update({
  id: '/labs',
  path: '/labs',
  getParentRoute: () => TableNexusRoute,
} as any)
const TableNexusMessengerRoute = TableNexusMessengerRouteImport.update({
  id: '/messenger',
  path: '/messenger',
  getParentRoute: () => TableNexusRoute,
} as any)
const TableNexusOfficeRoute = TableNexusOfficeRouteImport.update({
  id: '/office',
  path: '/office',
  getParentRoute: () => TableNexusRoute,
} as any)
const TableNexusPartyRoute = TableNexusPartyRouteImport.update({
  id: '/party',
  path: '/party',
  getParentRoute: () => TableNexusRoute,
} as any)
const TableSheetsSheetIdRoute = TableSheetsSheetIdRouteImport.update({
  id: '/$sheetId',
  path: '/$sheetId',
  getParentRoute: () => TableSheetsRoute,
} as any)
const TableVaultListingIdRoute = TableVaultListingIdRouteImport.update({
  id: '/$listingId',
  path: '/$listingId',
  getParentRoute: () => TableVaultRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/easy': typeof EasyRoute
  '/login': typeof LoginRoute
  '/meetings': typeof MeetingsRoute
  '/cart': typeof TableCartRoute
  '/duel': typeof TableDuelRoute
  '/events': typeof TableEventsRoute
  '/floor': typeof TableFloorRouteWithChildren
  '/hall': typeof TableHallRoute
  '/nexus': typeof TableNexusRouteWithChildren
  '/penny': typeof TablePennyRoute
  '/sell': typeof TableSellRoute
  '/sheets': typeof TableSheetsRouteWithChildren
  '/vault': typeof TableVaultRouteWithChildren
  '/api/rtc': typeof ApiRtcRoute
  '/floor/$tableId': typeof TableFloorTableIdRoute
  '/nexus/approach': typeof TableNexusApproachRoute
  '/nexus/garage': typeof TableNexusGarageRoute
  '/nexus/labs': typeof TableNexusLabsRoute
  '/nexus/messenger': typeof TableNexusMessengerRoute
  '/nexus/office': typeof TableNexusOfficeRoute
  '/nexus/party': typeof TableNexusPartyRoute
  '/sheets/$sheetId': typeof TableSheetsSheetIdRoute
  '/vault/$listingId': typeof TableVaultListingIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/nexus/': typeof TableNexusIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/easy': typeof EasyRoute
  '/login': typeof LoginRoute
  '/meetings': typeof MeetingsRoute
  '/cart': typeof TableCartRoute
  '/duel': typeof TableDuelRoute
  '/events': typeof TableEventsRoute
  '/floor': typeof TableFloorRouteWithChildren
  '/hall': typeof TableHallRoute
  '/penny': typeof TablePennyRoute
  '/sell': typeof TableSellRoute
  '/sheets': typeof TableSheetsRouteWithChildren
  '/vault': typeof TableVaultRouteWithChildren
  '/api/rtc': typeof ApiRtcRoute
  '/floor/$tableId': typeof TableFloorTableIdRoute
  '/nexus/approach': typeof TableNexusApproachRoute
  '/nexus/garage': typeof TableNexusGarageRoute
  '/nexus/labs': typeof TableNexusLabsRoute
  '/nexus/messenger': typeof TableNexusMessengerRoute
  '/nexus/office': typeof TableNexusOfficeRoute
  '/nexus/party': typeof TableNexusPartyRoute
  '/sheets/$sheetId': typeof TableSheetsSheetIdRoute
  '/vault/$listingId': typeof TableVaultListingIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/nexus': typeof TableNexusIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_table': typeof TableRouteWithChildren
  '/easy': typeof EasyRoute
  '/login': typeof LoginRoute
  '/meetings': typeof MeetingsRoute
  '/_table/cart': typeof TableCartRoute
  '/_table/duel': typeof TableDuelRoute
  '/_table/events': typeof TableEventsRoute
  '/_table/floor': typeof TableFloorRouteWithChildren
  '/_table/hall': typeof TableHallRoute
  '/_table/nexus': typeof TableNexusRouteWithChildren
  '/_table/penny': typeof TablePennyRoute
  '/_table/sell': typeof TableSellRoute
  '/_table/sheets': typeof TableSheetsRouteWithChildren
  '/_table/vault': typeof TableVaultRouteWithChildren
  '/api/rtc': typeof ApiRtcRoute
  '/_table/floor/$tableId': typeof TableFloorTableIdRoute
  '/_table/nexus/approach': typeof TableNexusApproachRoute
  '/_table/nexus/garage': typeof TableNexusGarageRoute
  '/_table/nexus/labs': typeof TableNexusLabsRoute
  '/_table/nexus/messenger': typeof TableNexusMessengerRoute
  '/_table/nexus/office': typeof TableNexusOfficeRoute
  '/_table/nexus/party': typeof TableNexusPartyRoute
  '/_table/sheets/$sheetId': typeof TableSheetsSheetIdRoute
  '/_table/vault/$listingId': typeof TableVaultListingIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_table/nexus/': typeof TableNexusIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/easy'
    | '/login'
    | '/meetings'
    | '/cart'
    | '/duel'
    | '/events'
    | '/floor'
    | '/hall'
    | '/nexus'
    | '/penny'
    | '/sell'
    | '/sheets'
    | '/vault'
    | '/api/rtc'
    | '/floor/$tableId'
    | '/nexus/approach'
    | '/nexus/garage'
    | '/nexus/labs'
    | '/nexus/messenger'
    | '/nexus/office'
    | '/nexus/party'
    | '/sheets/$sheetId'
    | '/vault/$listingId'
    | '/api/auth/$'
    | '/nexus/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/easy'
    | '/login'
    | '/meetings'
    | '/cart'
    | '/duel'
    | '/events'
    | '/floor'
    | '/hall'
    | '/penny'
    | '/sell'
    | '/sheets'
    | '/vault'
    | '/api/rtc'
    | '/floor/$tableId'
    | '/nexus/approach'
    | '/nexus/garage'
    | '/nexus/labs'
    | '/nexus/messenger'
    | '/nexus/office'
    | '/nexus/party'
    | '/sheets/$sheetId'
    | '/vault/$listingId'
    | '/api/auth/$'
    | '/nexus'
  id:
    | '__root__'
    | '/'
    | '/_table'
    | '/easy'
    | '/login'
    | '/meetings'
    | '/_table/cart'
    | '/_table/duel'
    | '/_table/events'
    | '/_table/floor'
    | '/_table/hall'
    | '/_table/nexus'
    | '/_table/penny'
    | '/_table/sell'
    | '/_table/sheets'
    | '/_table/vault'
    | '/api/rtc'
    | '/_table/floor/$tableId'
    | '/_table/nexus/approach'
    | '/_table/nexus/garage'
    | '/_table/nexus/labs'
    | '/_table/nexus/messenger'
    | '/_table/nexus/office'
    | '/_table/nexus/party'
    | '/_table/sheets/$sheetId'
    | '/_table/vault/$listingId'
    | '/api/auth/$'
    | '/_table/nexus/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TableRoute: typeof TableRouteWithChildren
  EasyRoute: typeof EasyRoute
  LoginRoute: typeof LoginRoute
  MeetingsRoute: typeof MeetingsRoute
  ApiRtcRoute: typeof ApiRtcRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_table': {
      id: '/_table'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof TableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/easy': {
      id: '/easy'
      path: '/easy'
      fullPath: '/easy'
      preLoaderRoute: typeof EasyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings': {
      id: '/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof MeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_table/cart': {
      id: '/_table/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof TableCartRouteImport
      parentRoute: typeof TableRoute
    }
    '/_table/duel': {
      id: '/_table/duel'
      path: '/duel'
      fullPath: '/duel'
      preLoaderRoute: typeof TableDuelRouteImport
      parentRoute: typeof TableRoute
    }
    '/_table/events': {
      id: '/_table/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof TableEventsRouteImport
      parentRoute: typeof TableRoute
    }
    '/_table/floor': {
      id: '/_table/floor'
      path: '/floor'
      fullPath: '/floor'
      preLoaderRoute: typeof TableFloorRouteImport
      parentRoute: typeof TableRoute
    }
    '/_table/hall': {
      id: '/_table/hall'
      path: '/hall'
      fullPath: '/hall'
      preLoaderRoute: typeof TableHallRouteImport
      parentRoute: typeof TableRoute
    }
    '/_table/nexus': {
      id: '/_table/nexus'
      path: '/nexus'
      fullPath: '/nexus'
      preLoaderRoute: typeof TableNexusRouteImport
      parentRoute: typeof TableRoute
    }
    '/_table/penny': {
      id: '/_table/penny'
      path: '/penny'
      fullPath: '/penny'
      preLoaderRoute: typeof TablePennyRouteImport
      parentRoute: typeof TableRoute
    }
    '/_table/sell': {
      id: '/_table/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof TableSellRouteImport
      parentRoute: typeof TableRoute
    }
    '/_table/sheets': {
      id: '/_table/sheets'
      path: '/sheets'
      fullPath: '/sheets'
      preLoaderRoute: typeof TableSheetsRouteImport
      parentRoute: typeof TableRoute
    }
    '/_table/vault': {
      id: '/_table/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof TableVaultRouteImport
      parentRoute: typeof TableRoute
    }
    '/api/rtc': {
      id: '/api/rtc'
      path: '/api/rtc'
      fullPath: '/api/rtc'
      preLoaderRoute: typeof ApiRtcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_table/floor/$tableId': {
      id: '/_table/floor/$tableId'
      path: '/$tableId'
      fullPath: '/floor/$tableId'
      preLoaderRoute: typeof TableFloorTableIdRouteImport
      parentRoute: typeof TableFloorRoute
    }
    '/_table/nexus/': {
      id: '/_table/nexus/'
      path: '/'
      fullPath: '/nexus/'
      preLoaderRoute: typeof TableNexusIndexRouteImport
      parentRoute: typeof TableNexusRoute
    }
    '/_table/nexus/approach': {
      id: '/_table/nexus/approach'
      path: '/approach'
      fullPath: '/nexus/approach'
      preLoaderRoute: typeof TableNexusApproachRouteImport
      parentRoute: typeof TableNexusRoute
    }
    '/_table/nexus/garage': {
      id: '/_table/nexus/garage'
      path: '/garage'
      fullPath: '/nexus/garage'
      preLoaderRoute: typeof TableNexusGarageRouteImport
      parentRoute: typeof TableNexusRoute
    }
    '/_table/nexus/labs': {
      id: '/_table/nexus/labs'
      path: '/labs'
      fullPath: '/nexus/labs'
      preLoaderRoute: typeof TableNexusLabsRouteImport
      parentRoute: typeof TableNexusRoute
    }
    '/_table/nexus/messenger': {
      id: '/_table/nexus/messenger'
      path: '/messenger'
      fullPath: '/nexus/messenger'
      preLoaderRoute: typeof TableNexusMessengerRouteImport
      parentRoute: typeof TableNexusRoute
    }
    '/_table/nexus/office': {
      id: '/_table/nexus/office'
      path: '/office'
      fullPath: '/nexus/office'
      preLoaderRoute: typeof TableNexusOfficeRouteImport
      parentRoute: typeof TableNexusRoute
    }
    '/_table/nexus/party': {
      id: '/_table/nexus/party'
      path: '/party'
      fullPath: '/nexus/party'
      preLoaderRoute: typeof TableNexusPartyRouteImport
      parentRoute: typeof TableNexusRoute
    }
    '/_table/sheets/$sheetId': {
      id: '/_table/sheets/$sheetId'
      path: '/$sheetId'
      fullPath: '/sheets/$sheetId'
      preLoaderRoute: typeof TableSheetsSheetIdRouteImport
      parentRoute: typeof TableSheetsRoute
    }
    '/_table/vault/$listingId': {
      id: '/_table/vault/$listingId'
      path: '/$listingId'
      fullPath: '/vault/$listingId'
      preLoaderRoute: typeof TableVaultListingIdRouteImport
      parentRoute: typeof TableVaultRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TableFloorRouteChildren {
  TableFloorTableIdRoute: typeof TableFloorTableIdRoute
}

const TableFloorRouteChildren: TableFloorRouteChildren = {
  TableFloorTableIdRoute: TableFloorTableIdRoute,
}

const TableFloorRouteWithChildren = TableFloorRoute._addFileChildren(
  TableFloorRouteChildren,
)

interface TableNexusRouteChildren {
  TableNexusApproachRoute: typeof TableNexusApproachRoute
  TableNexusGarageRoute: typeof TableNexusGarageRoute
  TableNexusLabsRoute: typeof TableNexusLabsRoute
  TableNexusMessengerRoute: typeof TableNexusMessengerRoute
  TableNexusOfficeRoute: typeof TableNexusOfficeRoute
  TableNexusPartyRoute: typeof TableNexusPartyRoute
  TableNexusIndexRoute: typeof TableNexusIndexRoute
}

const TableNexusRouteChildren: TableNexusRouteChildren = {
  TableNexusApproachRoute: TableNexusApproachRoute,
  TableNexusGarageRoute: TableNexusGarageRoute,
  TableNexusLabsRoute: TableNexusLabsRoute,
  TableNexusMessengerRoute: TableNexusMessengerRoute,
  TableNexusOfficeRoute: TableNexusOfficeRoute,
  TableNexusPartyRoute: TableNexusPartyRoute,
  TableNexusIndexRoute: TableNexusIndexRoute,
}

const TableNexusRouteWithChildren = TableNexusRoute._addFileChildren(
  TableNexusRouteChildren,
)

interface TableSheetsRouteChildren {
  TableSheetsSheetIdRoute: typeof TableSheetsSheetIdRoute
}

const TableSheetsRouteChildren: TableSheetsRouteChildren = {
  TableSheetsSheetIdRoute: TableSheetsSheetIdRoute,
}

const TableSheetsRouteWithChildren = TableSheetsRoute._addFileChildren(
  TableSheetsRouteChildren,
)

interface TableVaultRouteChildren {
  TableVaultListingIdRoute: typeof TableVaultListingIdRoute
}

const TableVaultRouteChildren: TableVaultRouteChildren = {
  TableVaultListingIdRoute: TableVaultListingIdRoute,
}

const TableVaultRouteWithChildren = TableVaultRoute._addFileChildren(
  TableVaultRouteChildren,
)

interface TableRouteChildren {
  TableCartRoute: typeof TableCartRoute
  TableDuelRoute: typeof TableDuelRoute
  TableEventsRoute: typeof TableEventsRoute
  TableFloorRoute: typeof TableFloorRouteWithChildren
  TableHallRoute: typeof TableHallRoute
  TableNexusRoute: typeof TableNexusRouteWithChildren
  TablePennyRoute: typeof TablePennyRoute
  TableSellRoute: typeof TableSellRoute
  TableSheetsRoute: typeof TableSheetsRouteWithChildren
  TableVaultRoute: typeof TableVaultRouteWithChildren
}

const TableRouteChildren: TableRouteChildren = {
  TableCartRoute: TableCartRoute,
  TableDuelRoute: TableDuelRoute,
  TableEventsRoute: TableEventsRoute,
  TableFloorRoute: TableFloorRouteWithChildren,
  TableHallRoute: TableHallRoute,
  TableNexusRoute: TableNexusRouteWithChildren,
  TablePennyRoute: TablePennyRoute,
  TableSellRoute: TableSellRoute,
  TableSheetsRoute: TableSheetsRouteWithChildren,
  TableVaultRoute: TableVaultRouteWithChildren,
}

const TableRouteWithChildren = TableRoute._addFileChildren(TableRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TableRoute: TableRouteWithChildren,
  EasyRoute: EasyRoute,
  LoginRoute: LoginRoute,
  MeetingsRoute: MeetingsRoute,
  ApiRtcRoute: ApiRtcRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
